steps:
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'install' ]
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'build production' ]
- name: 'gcr.io/ptspace-web-dev/firebase'
  args: [ 'deploy', '-P', 'dashfit-dev', '--token', '1/qUhkWPY6bowLdBcAPCrSjvydRXYDoWmStc_DAwjvo-k]']
